### ISSUE TITLE
custom login packets support?

### ISSUE THREAD

**Issue by paj1s** [VelocityPowered/CrossStitch#13]
Some mods like mighty mail doesn't work behind the proxy because it needs to send data from the server to the client.

**Comment by astei** [comment]
Velocity will gladly forward plugin messages from the server to the client. Aside from that you provide zero useful information aside from "it dun work pl0x fix".

You're not reporting a bug in CrossStitch as far as I can tell.

**Comment by paj1s** [comment]
Well maybe that's because i don't know. I have mod called mighty mail. When trying to place a wooden mailbox the game crashes. I have informed the devs of the mod and they told me it's because the mod doesn't like to work behind proxy because: "servers behind proxy don't support mods sending custom data during the login phase. Hence the config data doesn't get sent to the client.". So im here, this mod should implement the connection between the client - proxy - server. And now you tell me that velocity does support it soo?

**Comment by astei** [comment]
I missed the word "login", but Velocity has all the APIs the author needs to easily add the required login plugin message support. It shouldn't be more than a few hours of work, and should require very little maintenance. [I made such a sample plugin for Origins](https://github.com/astei/origins-velocity-adapter).

**Comment by astei** [comment]
I can't support login plugin messages in this mod because there is no sane strategy to handle login plugin messages in a generic fashion aside from mod authors providing an adapter for it (which could be as simple as replaying the message, or something more complex).
