### ISSUE TITLE
Server change management

### ISSUE THREAD

**Issue by campbebj** [VelocityPowered/CrossStitch#2]
Have you considered some sort of support to help more fabric <-> velocity interaction around server changing.

Im trying to figure out how to change servers for players without them having to type the command. 

If we could figure out some way to forward a command to velocity (such as from a command block, or even from eventually another mod) that would be really cool. 

Thoughts?

**Comment by astei** [comment]
Haven't really looked at the issue tracker. Thankfully, Velocity already supports the BungeeCord plugin messaging channel mechanism, which is already standard in the Bukkit/Spigot/Paper world and is just as applicable to Fabric. The only notable difference is that you need to send a message using the channel `bungeecord:main`.
